# Generated by Django 4.2.30 on 2026-06-11 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_following', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_follower', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('following', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='organizationfollowing',
            constraint=models.CheckConstraint(check=models.Q(('organization', models.F('following')), _negated=True), name='organization_cannot_follow_itself'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationfollowing',
            unique_together={('organization', 'following')},
        ),
        migrations.AddConstraint(
            model_name='organizationfollower',
            constraint=models.CheckConstraint(check=models.Q(('organization', models.F('follower')), _negated=True), name='organization_cannot_become_follower_of_itself'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationfollower',
            unique_together={('organization', 'follower')},
        ),
    ]
