# Generated by Django 4.2.30 on 2026-06-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('LOGIN', '0003_newuser_last_login_act_alter_newuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
