# Generated by Django 4.2.30 on 2026-06-02 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('bio_pitcure', models.ImageField(blank=True, null=True, upload_to='organizationProfile/')),
                ('type', models.CharField(choices=[('Pvt', 'Private'), ('Pub', 'Public')], default='Pvt', max_length=3)),
                ('body', models.TextField()),
                ('founder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
