# Generated by Django 4.2.30 on 2026-06-11 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BLOG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.BooleanField(db_index=True, default=True)),
                ('founder_pin', models.BooleanField(db_index=True, default=False)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinnedblog', to='BLOG.blog')),
            ],
        ),
    ]
