# Generated by Django 4.2.30 on 2026-06-15 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinblog',
            name='pin_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pinblog',
            unique_together={('blog', 'pin_by')},
        ),
    ]
