# Generated by Django 4.2.30 on 2026-06-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0002_initial'),
        ('Pin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinblog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinnedblog', to='BLOG.blog'),
        ),
    ]
