# Generated by Django 4.2.30 on 2026-06-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('LOGIN', '0004_alter_newuser_organization_and_more'),
        ('BLOG', '0006_remove_blog_pin_pinblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='organization',
        ),
        migrations.AlterField(
            model_name='organizationfollower',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='organizationfollower',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_follower', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='organizationfollowing',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='organizationfollowing',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_following', to='organization.organization'),
        ),
        migrations.DeleteModel(
            name='Organiztion',
        ),
    ]
