# Generated by Django 4.2.30 on 2026-06-14 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BLOG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_read', to='BLOG.blog')),
            ],
        ),
    ]
