# Generated by Django 4.2.30 on 2026-06-11 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Read', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogread',
            name='read_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='blogread',
            unique_together={('blog', 'read_by')},
        ),
    ]
